star: true
minChildren: 2
maxChildren: 4
maxResultsPerPage: 25
defaultSearchRadius: .5
maxAllowableSearchRadius: 50
findNearCoordinatePairObservableCacheDefaultSize: 1000
findAllObservableCacheDefaultSize: 500000