star: true
minChildren: 2
maxChildren: 4
maxResultsPerPage: 25
defaultSearchRadius: .5
maxAllowableSearchRadius: 50
findNearObservableCacheInitialCapacity: 1000
findAllObservableCacheInitialCapacity: 100000