---
apiVersion: v1
kind: Pod
metadata:
  name: rest-geospatial
  labels:
    app: rest-geospatial
spec:
  containers:
  - name: ephemeral-reactive-geospatial-rest-api
    image: joshdurbin/ephemeral-reactive-geospatial-rest-api:latest
    ports:
    - containerPort: 5050
      name: app-port
---
apiVersion: v1
kind: Service
metadata:
  name: rest-geospatial-svc
  labels:
    name: rest-geospatial-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: app-port
  selector:
    app: rest-geospatial
